name: Linux CMake Clang

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  BUILD_TYPE: Debug
  RISCV: /opt/riscv

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=clang

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Prepare Test Env
      run: sudo RISCV=${{env.RISCV}} ./.github/riscv_tests_env.sh

    - name: Test
      working-directory: ${{github.workspace}}/test
      run: RISCV=${{env.RISCV}} ./run_isa_tests.sh
